import React from 'react'; // Import React if you're using JSX
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import "./globals.css"; // Assuming this is the correct path to your global CSS file

export const metadata = {
    title: "Imdb clone",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const inter = { className: "your-inter-class-name" }; // You need to define the 'inter' variable
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header/>
                {children}
            </body>
        </html>
    );
}
